### ISSUE TITLE
работа с БД

### ISSUE THREAD

**Issue by apkuznetsov** [apkuznetsov/haulmont-test-task#1]
- [x] Пациент
  - Имя
  - Фамилия
  - Отчество
  - Телефон
---------------------
- [x] Врач
  - Имя
  - Фамилия
  - Отчество
  - Специализация
---------------------
- [x] Рецепт
  - Описание
  - Пациент
  - Врач
  - Дата создания
  - Срок действия
  - Приоритет
- [x] Рецепт может иметь один из приоритетов: Нормальный, Cito (Срочный), Statim (Немедленный).
---------------------
Система должна иметь следующие функции:
- [x] Отображение списка пациентов
- [x] Добавление нового пациента, редактирование и удаление существующего
- [x] Отображение списка врачей
- [x] Отображение статистической информации по количеству рецептов, выписанных врачами
- [x] Добавление нового врача, редактирование и удаление существующего
- [x] Отображения списка рецептов
- [x] Фильтрация списка рецептов по описанию, приоритету и пациенту
- [x] Добавление нового рецепта, редактирование и удаление существующего

**Comment by kouznts** [comment]
Рецепт может иметь один из приоритетов: Нормальный, Cito (Срочный), Statim (Немедленный).

**Comment by kouznts** [comment]
Система должна иметь следующие функции:
- [ ] Отображение списка пациентов
- [ ] Добавление нового пациента, редактирование и удаление существующего
- [ ] Отображение списка врачей
- [ ] Отображение статистической информации по количеству рецептов, выписанных врачами
- [ ] Добавление нового врача, редактирование и удаление существующего
- [ ] Отображения списка рецептов
- [ ] Фильтрация списка рецептов по описанию, приоритету и пациенту
- [ ] Добавление нового рецепта, редактирование и удаление существующего

**Comment by kouznts** [comment]
- [ ] Доступ к данным через JDBC или JPA
- [ ] Не используйте JPAContainer из Vaadin. Ваш код доступа к данным должен быть абстрагирован от UI
- [ ] Сервер баз данных: HSQLDB в in-process режиме (http://hsqldb.org/doc/2.0/guide/running-chapt.html#rgc_inprocess)

**Comment by kouznts** [comment]
- [ ] SQL-скрипт создания таблиц в базе данных в виде отдельного файла проекта
- [ ] Примечание: требуется SQL-скрипт создания всех необходимых объектов в БД, написанный вручную
